DROP TABLE IF EXISTS TBL_EMPLOYEES;
 
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);


DROP TABLE IF EXISTS CARS;

CREATE TABLE CARS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  make VARCHAR(250) NOT NULL,
  model VARCHAR(250) DEFAULT NULL,
  modelYear VARCHAR DEFAULT NULL,
  regNumber VARCHAR(250) NOT NULL,
  UNIQUE (regNumber)
);

DROP TABLE IF EXISTS DRIVERS;

CREATE TABLE DRIVERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  address VARCHAR(250) DEFAULT NULL,
  licenseNumber VARCHAR(250) NOT NULL,
  availableFrom TIME NOT NULL,
  availableTo TIME NOT NULL,
  UNIQUE (licenseNumber)
);


DROP TABLE IF EXISTS CAR_ALLOTMENTS;

CREATE TABLE CAR_ALLOTMENTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  driverId INT NOT NULL,
  carId INT NOT NULL,
  driverName VARCHAR(250) NOT NULL,
  driverLicenseNumber VARCHAR(250) NOT NULL,
  carRegNumber VARCHAR(250) NOT NULL,
  driverAvailableFrom TIME NOT NULL,
  driverAvailableTo TIME NOT NULL,
  UNIQUE (driverId)
);

DROP TABLE IF EXISTS CAR_BOOKINGS;

CREATE TABLE CAR_BOOKINGS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userIdName VARCHAR(250) NOT NULL,
  driverId INT NOT NULL,
  bookingFrom TIME NOT NULL,
  bookingTo TIME NOT NULL,
  isActive BOOLEAN NOT NULL,
  bookingStatus VARCHAR(250) NOT NULL,
  carId INT,
  carRegNumber VARCHAR(250),
  driverName VARCHAR(250),
  driverLicenseNumber VARCHAR(250),
  bookingCharge DECIMAL,
  CONSTRAINT user_booking UNIQUE (userIdName, bookingStatus, isActive)
);